### ISSUE TITLE
How to override force flag?

### ISSUE THREAD

**Issue by amanvishnani** [CircleCI-Public/heroku-orb#10]
I want to set force flag to true.

Docs do not mention the Env variable to set the force flag.
If possible please guide me. 
I am new to circle ci and orbs.

**Comment by a14m** [comment]
You can provide the force option to the `deploy-via-git` command (Ref: https://circleci.com/orbs/registry/orb/circleci/heroku )

you can use a similar code to this
```
jobs:
  # deploy master branch 
  deploy-staging:
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          force: true
          branch: master
```
