### ISSUE TITLE
deploy-via-git bash script error

### ISSUE THREAD

**Issue by makstaks** [CircleCI-Public/heroku-orb#13]
**Orb Version**

1.2.0

**Describe the bug**
Getting an error with bash script

```
/bin/bash: line 4: heroku_url: command not found

Exited with code exit status 127
```

I think the `heroku_url` has some unwanted whitespace around the `=` sign, so it is being treated as a command instead of as a variable assignment.

**To Reproduce**

I'm using this orb via CircleCI, here is my configuration:

```
  deploy-production:
    executor: heroku/default
    environment:
      HEROKU_APP_NAME: <our app name>
    steps:
      - checkout
      - heroku/deploy-via-git:
          force: true
          branch: HEAD
```

**Expected behavior**

No errors when executing bash script.

**Additional context**

We were able to successfully deploy this morning with the previous version of the bash script:

```
#!/bin/bash -eo pipefail
if true;then
  force="-f"
fi
git push $force https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
```
