### ISSUE TITLE
how to enter a directory to deploy?

### ISSUE THREAD

**Issue by t-heu** [CircleCI-Public/heroku-orb#22]
how can i enter the backend directory to commit there on heroku?
```
version: 2.1
orbs:
  # node: circleci/node@3.0.0
  heroku: circleci/heroku@1.2.3
jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          command: cd backend
      - heroku/deploy-via-git
workflows:
  heroku_deploy:
    jobs:
      - deploy
```
