### ISSUE TITLE
Heroku Docker Container Support

### ISSUE THREAD

**Issue by jamesarosen** [CircleCI-Public/heroku-orb#6]
I'd love to be able to push Docker images to the [Heroku Container Registry](https://devcenter.heroku.com/articles/container-registry-and-runtime) from CircleCI.

I'm imagining something like this in my `config.yml`:
```yml
jobs:
  - heroku/container-push:
      app-name: my-app
      process-type: web
      tag: "$CIRCLE_SHA1"
```

CircleCI already has [documentation](https://circleci.com/docs/2.0/custom-images/#storing-images-in-a-docker-registry) for pushing a Docker image to a Docker registry, but that approach [requires installing and using the Heroku CLI](https://discuss.circleci.com/t/deployment-on-circleci-docker-heroku-does-not-work/26106).
